require("xav1t.plugin_config.tokyonight")
require("xav1t.plugin_config.lualine")
require("xav1t.plugin_config.nvim-tree")
require("xav1t.plugin_config.telescope")
require("xav1t.plugin_config.treesitter")
require("xav1t.plugin_config.lsp_config")
require("xav1t.plugin_config.completions")
